spring:
  config:
    import: 'optional:consul:'
  application:
    name: nst-service
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        watch.enabled: true
        fail-fast: true
#        default-context: application
#        profile-separator: "-"
        format: yaml